build:
  maxIssues: 10
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

complexity:
  active: true
  ComplexInterface:
    threshold: 10
  CyclomaticComplexMethod:
    threshold: 15
  LongMethod:
    threshold: 80
  LongParameterList:
    functionThreshold: 7
    constructorThreshold: 7
  NestedBlockDepth:
    threshold: 4
  StringLiteralDuplication:
    active: false
  TooManyFunctions:
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 15
    thresholdInEnums: 15

naming:
  FunctionNaming:
    active: true
    excludes: [
      '**/test/**',
      '**/androidTest/**',
      '**/commonTest/**',
      '**/jvmTest/**',
      '**/androidUnitTest/**',
      '**/androidInstrumentedTest/**',
      '**/jsTest/**',
      '**/iosTest/**'
    ]
    functionPattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
    ignoreAnnotated: [ 'Composable' ]

style:
  NewLineAtEndOfFile:
    active: false